server=/douyin.com/180.184.1.1
server=/douyinstatic.com/180.184.1.1
server=/snssdk.com/180.184.1.1
server=/byteimg.com/180.184.1.1
server=/bytedance.com/180.184.1.1
server=/toutiao.com/180.184.1.1
server=/ixigua.com/180.184.1.1
server=/douyinpic.com/180.184.1.1
server=/amemv.com/180.184.1.1
server=/bytecdn.cn/180.184.1.1