server=/microsoft.com/4.2.2.1
server=/microsoftonline.com/4.2.2.1
server=/msftconnecttest.com/4.2.2.1
server=/windowsupdate.com/4.2.2.1
server=/live.com/4.2.2.1
server=/live.net/4.2.2.1
server=/office365.com/4.2.2.1
server=/office.com/4.2.2.1
server=/onedrive.com/4.2.2.1
server=/microsoft.io/4.2.2.1
